/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ana
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pozorište");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCreateGlumac = new javax.swing.JMenuItem();
        jmiPretragaGlumca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiKreirajProjekciju = new javax.swing.JMenuItem();
        jmiNadjiProjekciju = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoggedUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoggedUser.setText("Ulogovani");

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Odjava");

        jMenu1.setText("Glumci");

        jmiCreateGlumac.setText("Kreiraj glumca");
        jMenu1.add(jmiCreateGlumac);

        jmiPretragaGlumca.setText(" Nađi glumca");
        jMenu1.add(jmiPretragaGlumca);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Projekcije");

        jmiKreirajProjekciju.setText("Kreiraj projekciju");
        jMenu2.add(jmiKreirajProjekciju);

        jmiNadjiProjekciju.setText(" Nađi projekciju");
        jMenu2.add(jmiNadjiProjekciju);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLoggedUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblLoggedUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblLoggedUser() {
        return lblLoggedUser;
    }

    public void btnLogoutAddActionListener(ActionListener actionListener) {
        btnLogout.addActionListener(actionListener);
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public void jmiCreateGlumacAddActionListener(ActionListener actionListener) {
        jmiCreateGlumac.addActionListener(actionListener);
    }

    public void jmiPretragaGlumcaAddActionListener(ActionListener actionListener) {
        jmiPretragaGlumca.addActionListener(actionListener);
    }

    public void jmiKreirajProjekcijuAddActionListener(ActionListener actionListener) {
        jmiKreirajProjekciju.addActionListener(actionListener);
    }
    
    public void jmiNadjiProjekcijuAddActionListener(ActionListener actionListener){
        jmiNadjiProjekciju.addActionListener(actionListener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiCreateGlumac;
    private javax.swing.JMenuItem jmiKreirajProjekciju;
    private javax.swing.JMenuItem jmiNadjiProjekciju;
    private javax.swing.JMenuItem jmiPretragaGlumca;
    private javax.swing.JLabel lblLoggedUser;
    // End of variables declaration//GEN-END:variables
}
