/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ana
 */
public class PretragaProjekcijaForm extends javax.swing.JDialog {

    /**
     * Creates new form PretragaProjekcijaForma
     */
    public PretragaProjekcijaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivPredstave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjekcije = new javax.swing.JTable();
        btnPretraga = new javax.swing.JButton();
        btnResetuj = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Unesite naziv predstave");

        tblProjekcije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProjekcije);

        btnPretraga.setBackground(new java.awt.Color(204, 204, 204));
        btnPretraga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPretraga.setText("Pretraga");

        btnResetuj.setBackground(new java.awt.Color(204, 204, 204));
        btnResetuj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetuj.setText("Resetuj");

        btnDetalji.setBackground(new java.awt.Color(204, 204, 204));
        btnDetalji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetalji.setText("Detalji o projekciji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetuj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNazivPredstave, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivPredstave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalji))
                .addGap(18, 18, 18)
                .addComponent(btnPretraga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnResetuj)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnPretraga() {
        return btnPretraga;
    }
    public void btnPretragaAddActionListener(ActionListener actionListener){
        btnPretraga.addActionListener(actionListener);
    }

    public JTable getTblProjekcije() {
        return tblProjekcije;
    }

    public JTextField getTxtNazivPredstave() {
        return txtNazivPredstave;
    }

    public JButton getBtnResetuj() {
        return btnResetuj;
    }
    
    public void btnResetujAddActionListener(ActionListener actionListener){
        btnResetuj.addActionListener(actionListener);
    }

    public JButton getBtnDetalji() {
        return btnDetalji;
    }
    
    public void btnDetaljiAddActionListener(ActionListener actionListener){
        btnDetalji.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProjekcije;
    private javax.swing.JTextField txtNazivPredstave;
    // End of variables declaration//GEN-END:variables
}
